### ISSUE TITLE
An error occurs when launching a project through Icarus

### ISSUE THREAD

**Issue by votechok** [TerosTechnology/vscode-terosHDL#508]
I took a test project of terosHDL for icarus.
An error occurs when launching a project through icarus using the panel "run".
```
2023-11-29 17:52:19.196 [info] Traceback (most recent call last):
  File "c:\Users\User\.vscode\extensions\teros-technology.teroshdl-5.0.12\node_modules\teroshdl2\out\project_manager\tool\edalize\run_edalize.py", line 72, in <module>

2023-11-29 17:52:19.197 [info] 
************************************************************************************************
---> Build directory: C:\Users\User\.teroshdl\build

2023-11-29 17:52:19.197 [info]     os.makedirs(working_directory)
  File "<frozen os>", line 225, in makedirs
FileExistsError: [WinError 183] ���������� ������� ����, ��� ��� �� ��� ����������: 'C:\\Users\\User\\.teroshdl\\build'
```
Apparently, when Python tries to create a file, it sees that the file exists and throws an error. I don't understand how this can be fixed.

**Comment by qarlosalberto** [comment]
Have you tried to delete the build path? `C:\Users\User\.teroshdl\build`

**Comment by votechok** [comment]
This is what I tried to do too. But I didn't find the .teroshdl folder in the specified location

**Comment by votechok** [comment]
![изображение](https://github.com/TerosTechnology/vscode-terosHDL/assets/98825020/36614397-711d-43ab-96b8-2e72b61ea5ef)

**Comment by qarlosalberto** [comment]
try to create the folder: `C:\Users\User\.teroshdl\build`

**Comment by votechok** [comment]
created a folder, but the result is the same
