### ISSUE TITLE
Formatter s3sv not working

### ISSUE THREAD

**Issue by IMucaMI** [TerosTechnology/vscode-terosHDL#670]
**Describe the bug**
When I try to run the source code formatter, nothing happens.
**Error**
```
2024-09-27 10:30:57.437 [error] [teros-technology.teroshdl] provider FAILED
2024-09-27 10:30:57.439 [error] TypeError: A dynamic import callback was not specified.
	at importModuleDynamicallyCallback (node:internal/modules/esm/utils:228:9)
	at initNodeModules (c:\Users\USER\.vscode\extensions\teros-technology.teroshdl-6.0.6\node_modules\pyodide\pyodide.js:9:802)
	at loadPyodide (c:\Users\USER\.vscode\extensions\teros-technology.teroshdl-6.0.6\node_modules\pyodide\pyodide.js:9:9398)
	at Pyodide.load (c:\Users\USER\.vscode\extensions\teros-technology.teroshdl-6.0.6\out\colibri\process\pyodide.js:54:34)
	at Pyodide.exec_python_code (c:\Users\USER\.vscode\extensions\teros-technology.teroshdl-6.0.6\out\colibri\process\pyodide.js:66:38)
	at S3sv.format_from_code_with_pyodide (c:\Users\USER\.vscode\extensions\teros-technology.teroshdl-6.0.6\out\colibri\formatter\s3sv.js:45:38)
	at S3sv.format_from_code (c:\Users\USER\.vscode\extensions\teros-technology.teroshdl-6.0.6\out\colibri\formatter\s3sv.js:32:27)
	at Formatter.format_from_code (c:\Users\USER\.vscode\extensions\teros-technology.teroshdl-6.0.6\out\colibri\formatter\formatter.js:57:26)
	at Formatter.format (c:\Users\USER\.vscode\extensions\teros-technology.teroshdl-6.0.6\out\teroshdl\features\formatter.js:88:40)
	at Object.provideDocumentFormattingEdits (c:\Users\USER\.vscode\extensions\teros-technology.teroshdl-6.0.6\out\teroshdl\features\formatter.js:157:48)
	at j.provideDocumentFormattingEdits (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:161:112565)
	at c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:161:141772
	at We.s (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:161:136041)
	at We.$provideDocumentFormattingEdits (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:161:141759)
	at y.S (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:158:5968)
	at y.Q (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:158:5734)
	at y.M (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:158:4729)
	at y.L (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:158:3602)
	at i.value (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:158:2297)
	at r.B (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:732)
	at r.fire (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:949)
	at a.fire (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:115:14463)
	at i.value (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:184:8635)
	at r.B (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:732)
	at r.fire (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:949)
	at a.fire (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:115:14463)
	at MessagePortMain.<anonymous> (c:\Users\USER\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:184:6761)
	at MessagePortMain.emit (node:events:519:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2619)
```
 - OS: Windows 10 x64
 - VSCode version version 1.93.1

**Comment by qarlosalberto** [comment]
It should be fixed in the new version on the market. Feel free to reopen the issue if it's not working.
